import css3Logo from '../../assets/logos/skills/css3.svg';
import herokuLogo from '../../assets/logos/skills/heroku.svg';
import nodeLogo from '../../assets/logos/skills/node-js.svg';
import reduxLogo from '../../assets/logos/skills/redux.svg';
import expressjsLogo from '../../assets/logos/skills/expressjs.svg';
import javascriptLogo from '../../assets/logos/skills/javascript.svg';
import photoshopLogo from '../../assets/logos/skills/photoshop.svg';
import sassLogo from '../../assets/logos/skills/sass.svg';
import firebaseLogo from '../../assets/logos/skills/firebase.svg';
import mongodbLogo from '../../assets/logos/skills/mongodb.svg';
import reactNativeLogo from '../../assets/logos/skills/react-native.svg';
import typescriptLogo from '../../assets/logos/skills/typescript.svg';
import googleLogo from '../../assets/logos/skills/google-cloud.svg';
import nextLogo from '../../assets/logos/skills/next-js.svg';
import reactLogo from '../../assets/logos/skills/react.svg';
import graphqlLogo from '../../assets/logos/skills/graphql.svg';
import d3jsLogo from '../../assets/logos/skills/d3.svg';
import html5Logo from '../../assets/logos/skills/html-5.svg';

export const projects = [
  {
    name: 'ALERZOSHOP PWA',
    employer: 'SKUAD PTE LTD.',
    desc: 'This is an e-commerce platform for Alerzo, one of the biggest B2B retailers in Nigeria. I worked as part of a remote team to build and maintain this for several months.',
    singleHandedly: false,
    remote: true,
    isFrontend: true,
    isBackend: false,
    isPersonal: false,
    pjLink: 'https://shop.alerzo.com/',
    codeLink: '',
    stack: [
      javascriptLogo,
      nextLogo,
      reduxLogo,
      graphqlLogo,
      firebaseLogo,
      googleLogo,
    ],
  },
  {
    name: 'ALERZOSHOP APP',
    employer: 'SKUAD PTE LTD.',
    desc: 'This is an e-commerce platform for Alerzo, one of the biggest B2B retailers in Nigeria. I worked as part of a remote team to build and maintain this for several months.',
    singleHandedly: false,
    remote: true,
    isFrontend: true,
    isBackend: false,
    isPersonal: false,
    pjLink:
      'https://play.google.com/store/apps/details?id=com.alerzoretailermobile&hl=en&gl=US',
    codeLink: '',
    stack: [javascriptLogo, reactNativeLogo, reduxLogo, firebaseLogo],
  },
  {
    name: 'KCCA MANE / KAMPALA AMBULANCE SERVICES',
    employer: 'OUTBOX (U) LTD.',
    desc: 'This is a General Welfare project called MaNE(Maternal and Newborn Health) for the KCCA (Kampala Capital City Authority) which is the governing authority of Kampala city. \n\nThis project was aimed at streamlining the provision of Emergency Services (Ambulances) for pregnant mothers during the total lockdown the City was subjected to as a result of the danger posed by the Covid-19 pandemic.\n\nThe app has since then been repurposed to provide emergency services to all citizens.',
    singleHandedly: false,
    remote: false,
    isFrontend: true,
    isBackend: false,
    isPersonal: false,
    pjLink:
      'https://play.google.com/store/apps/details?id=com.manecommunityapp',
    codeLink: '',
    stack: [
      javascriptLogo,
      reactNativeLogo,
      reduxLogo,
      firebaseLogo,
      googleLogo,
    ],
  },
  {
    name: 'WEYONJE CLIENT APP',
    employer: 'OUTBOX (U) LTD.',
    desc: 'Weyonje is a mobile application built to enable residents of Kampala City to request waste emptying services, track job orders, and make payment for services rendered.',
    singleHandedly: false,
    remote: false,
    isFrontend: true,
    isBackend: false,
    isPersonal: false,
    pjLink: 'https://play.google.com/store/apps/details?id=com.weyonjeclient',
    codeLink: '',
    stack: [
      javascriptLogo,
      reactNativeLogo,
      reduxLogo,
      firebaseLogo,
      googleLogo,
    ],
  },
  {
    name: 'WEYONJE VHT',
    employer: 'OUTBOX (U) LTD.',
    desc: 'Weyonje VHT is a mobile application built to allow certain offcials to provide vouchers for pit emptying services to vulnerable groups within the city. I built this app for the Kampala Capital City Authority (KCCA) as part of a team working for Outbox Uganda.',
    singleHandedly: true,
    remote: false,
    isFrontend: true,
    isBackend: false,
    isPersonal: false,
    pjLink: 'https://play.google.com/store/apps/details?id=com.weyonjeVHT',
    codeLink: '',
    stack: [
      javascriptLogo,
      reactNativeLogo,
      reduxLogo,
      firebaseLogo,
      googleLogo,
    ],
  },
  {
    name: 'WEYONJE DASHBOARD',
    employer: 'OUTBOX (U) LTD.',
    desc: 'The Weyonje Dashboard allows administrators to see and control the content of all the Weyonje Apps as well as to interface with users of all the apps.',
    singleHandedly: true,
    remote: false,
    isFrontend: true,
    isBackend: false,
    isPersonal: false,
    pjLink: 'https://new.weyonje.com/',
    codeLink: '',
    stack: [
      javascriptLogo,
      reactLogo,
      reduxLogo,
      firebaseLogo,
      googleLogo,
      nodeLogo,
      expressjsLogo,
      mongodbLogo,
      sassLogo,
      css3Logo,
    ],
  },
  {
    name: 'SMARTEC ELECTRONICS WEBSITE & DASHBOARD',
    employer: 'SMARTEC ELECTRONICS LTD.',
    desc: 'This is the home website & dashboard for Smartec Electronics Uganda, the offcial distributor of Hisense, Huawei and Changhong Electronics Products in Uganda. It is an e-commerce website and is currently in its maintenance stage where new features are occasionally commissioned. It has an admin dashboard that controls the website.',
    singleHandedly: true,
    remote: false,
    isFrontend: true,
    isBackend: true,
    isPersonal: false,
    pjLink: 'https://smartecelectronics.com/',
    codeLink: '',
    stack: [
      javascriptLogo,
      reactLogo,
      nextLogo,
      reduxLogo,
      nodeLogo,
      expressjsLogo,
      mongodbLogo,
      sassLogo,
      css3Logo,
      photoshopLogo,
    ],
  },
  {
    name: 'ALTX COMAS',
    employer: 'BURI AFRICA LTD.',
    desc: 'This is a private admin dashboard for Altx COMAS a Ugandan stock trading company. It is fully built and in a maintenance phase where new features are occasionally commissioned.',
    singleHandedly: true,
    remote: false,
    isFrontend: true,
    isBackend: false,
    isPersonal: false,
    pjLink: 'https://agency.altxafrica.com',
    codeLink: '',
    stack: [
      javascriptLogo,
      reactLogo,
      nextLogo,
      reduxLogo,
      nodeLogo,
      expressjsLogo,
      mongodbLogo,
      sassLogo,
      css3Logo,
      photoshopLogo,
    ],
  },

  {
    name: 'COVID INFOBOT',
    employer: 'PERSONAL',
    desc: 'The COVID InfoBot is a simple chatbot developed on Nodejs and deployed on Twilio. It was a response to a challenge by the ICT Ministry of Uganda to develop innovative solutions to combat the spread of COVID-19. The COVID Infobot dispenses general knowledge about COVID-19 and gathers new questions from users which are forwarded to its administrators. This InfoBot was built as part of a collaborative effort between myself and a colleague.\n\nYou can login to tthe dashboard with these credentials\nemail - prowori2@gmail.com password - 123\n\nTo test the Chatbot, text “Join ask-exciting“ to +1 (415) 523-8886 on Whatsapp, then text “Hey”',
    singleHandedly: false,
    remote: false,
    isFrontend: true,
    isBackend: true,
    isPersonal: true,
    pjLink: 'https://corona-infobot-web.herokuapp.com/',
    codeLink: 'https://github.com/Paul-Owori/corona_infobot_firebase',
    stack: [javascriptLogo, reactLogo, herokuLogo, nodeLogo, firebaseLogo],
  },

  // Personal
  {
    name: 'D3.js INTERACTIVE DASHBOARD',
    employer: 'PERSONAL',
    desc: 'The D3.js Interactive Dashboard was my attempt at exploring the potential of D3.js in creating interactive graphs and maps. It shows dummy medical data gathered from different facilities around the country about the vaccination rates of certain vaccines.',
    singleHandedly: true,
    remote: false,
    isFrontend: true,
    isBackend: false,
    isPersonal: true,
    pjLink: 'https://d3-interactive-dashboard.web.app/',
    codeLink: 'https://github.com/Paul-Owori/d3_js_interactive_demo',
    stack: [javascriptLogo, d3jsLogo, reactLogo, css3Logo, firebaseLogo],
  },
  {
    name: 'TRIP',
    employer: 'PERSONAL',
    desc: 'TRIP is a ride hailing application that connects transport service providers to potential clients. Unlike most other transport apps however, TRIP is designed to cater to persons with or without physical disabilities.',
    singleHandedly: true,
    remote: false,
    isFrontend: true,
    isBackend: false,
    isPersonal: true,
    pjLink: 'https://pada-rides.herokuapp.com/',
    codeLink: 'https://github.com/Paul-Owori/PADA-Rides',
    stack: [javascriptLogo, html5Logo, css3Logo, herokuLogo],
  },
];
